name: protego_vpn
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  go_router: ^12.0.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.7.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  connectivity_plus: ^4.0.2
  easy_localization: ^3.0.3
  url_launcher: ^6.2.1
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/languages/
   

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
       
 
 